import { MenuItem } from './menu-item.interface';
import { Permissions } from '@shared/authorization/permissions';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'dashboard',
    path: '/',
    permission: Permissions.DASHBOARD.VIEW,
  },
  {
    id: 'inventory',
    label: 'Inventory',
    icon: 'warehouse',
    permission: Permissions.PRODUCTS.READ,
    children: [
      {
        id: 'products',
        label: 'Products',
        icon: 'box',
        path: '/products',
        permission: Permissions.PRODUCTS.READ,
      },
      {
        id: 'finishes',
        label: 'Finishes',
        icon: 'finish',
        path: '/finishes',
        permission: Permissions.FINISHES.LIST,
      },
      {
        id: 'levels',
        label: 'Levels',
        icon: 'level',
        path: '/levels',
        permission: Permissions.LEVELS.LIST,
      },
      {
        id: 'suppliers',
        label: 'Suppliers',
        icon: 'supplier',
        path: '/suppliers',
        permission: Permissions.SUPPLIERS.LIST,
      },
      {
        id: 'brands',
        label: 'Brands',
        icon: 'tag',
        path: '/brands',
        permission: Permissions.BRANDS.READ,
      },
      {
        id: 'categories',
        label: 'Categories',
        icon: 'category',
        path: '/categories',
        permission: Permissions.CATEGORIES.READ,
      },
      {
        id: 'bundles',
        label: 'Bundles',
        icon: 'package',
        path: '/bundles',
        permission: Permissions.BUNDLES.LIST,
      },
      {
        id: 'slabs',
        label: 'Slabs',
        icon: 'layers',
        path: '/slabs',
        permission: Permissions.SLABS.LIST,
      },
    ],
  },
  {
    id: 'workshop',
    label: 'Workshop',
    icon: 'build',
    permission: Permissions.WORKSHOP_TOOLS.LIST,
    children: [
      {
        id: 'workshop-tools',
        label: 'Tools',
        icon: 'handyman',
        path: '/workshop/tools',
        permission: Permissions.WORKSHOP_TOOLS.LIST,
      },
      {
        id: 'workshop-materials',
        label: 'Materials',
        icon: 'inventory-2',
        path: '/workshop/materials',
        permission: Permissions.WORKSHOP_MATERIALS.LIST,
      },
      {
        id: 'workshop-categories',
        label: 'Categories',
        icon: 'category',
        path: '/workshop/categories',
        permission: Permissions.WORKSHOP_CATEGORIES.LIST,
      },
      {
        id: 'workshop-suppliers',
        label: 'Suppliers',
        icon: 'supplier',
        path: '/workshop/suppliers',
        permission: Permissions.WORKSHOP_SUPPLIERS.LIST,
      },
      {
        id: 'fabrication-drawings',
        label: 'Drawings',
        icon: 'supplier',
        path: 'fabrication/drawings',
        permission: Permissions.WORKSHOP_SUPPLIERS.LIST,
      },
    ],
  },
  {
    id: 'purchasing',
    label: 'Purchasing',
    icon: 'receipt',
    permission: Permissions.PURCHASE_INVOICES.READ,
    children: [
      {
        id: 'purchase-invoices',
        label: 'Invoices',
        icon: 'receipt-long',
        path: '/purchase-invoices',
        permission: Permissions.PURCHASE_INVOICES.READ,
      },
      {
        id: 'supplier-returns',
        label: 'Supplier Returns',
        icon: 'assignment-return',
        path: '/purchasing/supplier-returns',
        permission: Permissions.SUPPLIER_RETURNS.LIST,
      },
    ],
  },
  {
    id: 'projects',
    label: 'Projects',
    icon: 'construction',
    permission: Permissions.JOBS.READ,
    children: [
      {
        id: 'jobs',
        label: 'Jobs',
        icon: 'work',
        path: '/jobs',
        permission: Permissions.JOBS.READ,
      },
      {
        id: 'job-payments',
        label: 'Job Payments',
        icon: 'payments',
        path: '/job-payments',
        permission: Permissions.JOB_PAYMENTS.READ,
      },
    ],
  },
  {
    id: 'accounting',
    label: 'Accounting',
    icon: 'account-balance',
    permission: Permissions.ACCOUNTING.VIEW,
    children: [
      {
        id: 'invoice-payments',
        label: 'Invoice Payments',
        icon: 'payment',
        path: '/invoice-payments',
        permission: Permissions.INVOICE_PAYMENTS.READ,
      },
      {
        id: 'general-payments',
        label: 'General Payments',
        icon: 'swap-horiz',
        path: '/general-payments',
        permission: Permissions.GENERAL_PAYMENTS.READ,
      },
      {
        id: 'cashflow',
        label: 'Cashflow',
        icon: 'trending-up',
        path: '/accounting/cashflow',
        permission: Permissions.ACCOUNTING.VIEW,
      },
    ],
  },
  {
    id: 'users',
    label: 'Users',
    icon: 'people',
    permission: Permissions.USERS.READ,
    children: [
      {
        id: 'users-list',
        label: 'Users List',
        icon: 'person',
        path: '/users',
        permission: Permissions.USERS.READ,
      },
      {
        id: 'roles',
        label: 'Roles',
        icon: 'shield',
        path: '/roles',
        permission: Permissions.ROLES.READ,
      },
    ],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: 'settings',
    path: '/settings',
    permission: Permissions.SETTINGS.READ,
  },
  {
    id: 'profile',
    label: 'Profile',
    icon: 'person',
    path: '/profile',
    permission: Permissions.PROFILE.READ,
  },
];
