export enum PaymentCategory {
  SALARY = 'SALARY',
  RENT = 'RENT',
  UTILITIES = 'UTILITIES',
  TRANSPORT = 'TRANSPORT',
  MATERIAL_SALE = 'MATERIAL_SALE',
  CLIENT_ADVANCE = 'CLIENT_ADVANCE',
  SUPPLIER_REFUND = 'SUPPLIER_REFUND',
  BANK_FEES = 'BANK_FEES',
  OTHER_EXPENSE = 'OTHER_EXPENSE',
  OTHER_INCOME = 'OTHER_INCOME',
}
